version: '3.8'

services:
  mysql:
    image: bitnami/mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=aitivasi
      - MYSQL_PASSWORD=aitivasi
      - MYSQL_DATABASE=aitivasi
    ports:
      - "33060:3306"
    volumes:
      - mysql_data:/bitnami/mysql
    networks:
      - mysql_network

volumes:
  mysql_data:

networks:
  mysql_network:
    driver: bridge

